import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        // Pixel palette, usable directly as utilities.
        void: "var(--px-void)",
        panel: "var(--px-panel)",
        well: "var(--px-well)",
        ink: "var(--px-well)",
        line: "var(--px-line)",
        body: "var(--px-text)",
        dim: "var(--px-dim)",
        gold: "var(--px-gold)",
        golddk: "var(--px-gold-dk)",
        onbrass: "var(--px-on-accent)",
        green: "var(--px-green)",
        greendk: "var(--px-green-dk)",
        red: "var(--px-red)",
        reddk: "var(--px-red-dk)",
        blue: "var(--px-blue)",
        bluedk: "var(--px-blue-dk)",
        orange: "var(--px-orange)",
        // Legacy aliases from the previous world, repointed to pixel tokens.
        brass: "var(--px-gold)",
        turmeric: "var(--px-gold)",
        brassdeep: "var(--px-gold-dk)",
        parchment: "var(--px-text)",
        parchmentdim: "var(--px-dim)",
        sealred: "var(--px-red)",
        peacock: "var(--px-green)",
        maroon: "var(--px-red-dk)",
        archive: "var(--px-panel)",
        plate: "var(--px-panel)",
        sidebar: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
          primary: "var(--primary)",
          "primary-foreground": "var(--primary-foreground)",
          accent: "var(--accent)",
          "accent-foreground": "var(--accent-foreground)",
          border: "var(--border)",
          ring: "var(--ring)",
        },
      },
      fontFamily: {
        sans: ["var(--font-body)", "monospace"],
        body: ["var(--font-body)", "monospace"],
        pixel: ["var(--font-pixel)", "monospace"],
        display: ["var(--font-pixel)", "monospace"],
        mono: ["var(--font-body)", "monospace"],
      },
      borderRadius: {
        lg: "0px",
        md: "0px",
        sm: "0px",
        DEFAULT: "0px",
      },
      boxShadow: {
        px: "4px 4px 0 var(--px-shadow)",
        seal: "4px 4px 0 var(--px-shadow)",
      },
    },
  },
  plugins: [],
};

export default config;
