import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* shadcn / base-ui bridge */
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-fg)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        sidebar: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
          primary: "var(--primary)",
          "primary-foreground": "var(--primary-foreground)",
          accent: "var(--accent)",
          "accent-foreground": "var(--accent-fg)",
          border: "var(--border)",
          ring: "var(--ring)",
        },

        /* MACADAM semantic tokens */
        page: "var(--bg)",
        raise: "var(--bg-elev)",
        surface: "var(--surface)",
        sunken: "var(--surface-2)",
        hairline: "var(--line)",
        hairline2: "var(--line-strong)",
        ink: "var(--text)",
        ink2: "var(--text-2)",
        ink3: "var(--text-3)",
        signal: "var(--accent)",
        signal2: "var(--accent-strong)",
        onsignal: "var(--on-accent)",
        signalalt: "var(--accent-2)",
        ok: "var(--ok)",
        warn: "var(--warn)",
        bad: "var(--bad)",
        info: "var(--info)",

        /* Legacy pixel-world aliases — transitional, removed once pages migrate. */
        void: "var(--bg)",
        panel: "var(--surface)",
        well: "var(--surface-2)",
        line: "var(--line)",
        body: "var(--text)",
        dim: "var(--text-2)",
        gold: "var(--accent)",
        golddk: "var(--accent-strong)",
        onbrass: "var(--on-accent)",
        green: "var(--ok)",
        greendk: "var(--ok)",
        red: "var(--bad)",
        reddk: "var(--bad)",
        blue: "var(--info)",
        bluedk: "var(--info)",
        orange: "var(--warn)",
        brass: "var(--accent)",
        turmeric: "var(--accent)",
        brassdeep: "var(--accent-strong)",
        parchment: "var(--text)",
        parchmentdim: "var(--text-2)",
        sealred: "var(--bad)",
        peacock: "var(--ok)",
        maroon: "var(--bad)",
        archive: "var(--surface)",
        plate: "var(--surface)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "ui-sans-serif", "system-ui", "sans-serif"],
        pixel: ["var(--font-display)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        sm: "var(--r-1)",
        DEFAULT: "var(--r-2)",
        md: "var(--r-2)",
        lg: "var(--r-3)",
        xl: "var(--r-4)",
        "2xl": "var(--r-4)",
        "3xl": "var(--r-4)",
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        px: "var(--shadow-2)",
        seal: "var(--shadow-2)",
      },
      keyframes: {
        "mac-ignite": {
          "0%": { opacity: "0", transform: "translateY(10px)", clipPath: "inset(0 0 100% 0)" },
          "100%": { opacity: "1", transform: "none", clipPath: "inset(0 0 0 0)" },
        },
        "mac-pulse": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.45", transform: "scale(0.82)" },
        },
        "mac-pop": {
          "0%": { transform: "scale(0.92)" },
          "55%": { transform: "scale(1.04)" },
          "100%": { transform: "scale(1)" },
        },
        "mac-sonar": {
          "0%": { transform: "scale(0.6)", opacity: "0.7" },
          "100%": { transform: "scale(2.4)", opacity: "0" },
        },
        "mac-shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-3px)" },
          "40%": { transform: "translateX(3px)" },
          "60%": { transform: "translateX(-2px)" },
          "80%": { transform: "translateX(2px)" },
        },
      },
      animation: {
        "mac-ignite": "mac-ignite var(--dur-4) var(--ease-out) both",
        "mac-pulse": "mac-pulse 2.4s var(--ease-inout) infinite",
        "mac-pop": "mac-pop var(--dur-3) var(--ease-out) both",
        "mac-sonar": "mac-sonar 1.8s var(--ease-out) infinite",
        "mac-shake": "mac-shake 0.3s var(--ease-out) both",
      },
    },
  },
  plugins: [],
};

export default config;
